# config-repo/order-service.yml

server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=orders
    username: sa
    password: Admin!12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

# Add this property properly so it's resolvable
product:
  base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
